[package]
authors = ["Tavy <sabit@sabit.space>"]
name = "pepper"
version = "0.1.0"

[dependencies]
futures = "0.1.13"
route-recognizer = "0.1.11"
tokio-core = "0.1.6"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper"
optional = false
